### ISSUE TITLE
Properties like file paths shouldn't be defined in code

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#10]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/InitialiseEntities.java#L26

Properties like file paths should be defined in java code.  See if there's a way to create a property file for details like this.

**Comment by Gala-Gerrard** [comment]
config.yml file introduced to provide all locations of the input/output files
