### ISSUE TITLE
Unused Variables

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#16]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/Agreement.java#L17

sellCust, ticker and matchQ aren't used anywhere.  Unused variables can be removed

**Comment by Gala-Gerrard** [comment]
Addressed this using the code cleanup tool in Intellij
