### ISSUE TITLE
Uneeded Imports

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#17]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/Account.java#L4

A lot of your files have imports like Value here which aren't actually being used.  You can get rid of these by opening an individual file (or selecting an entire folder) and from the top taskbar selecting Code -> Optimize Import.  The shortcut for this is worth learning as you use this feature a lot.

**Comment by Gala-Gerrard** [comment]
Addressed this using the optimize import tool
