### ISSUE TITLE
Do you have to return dummy order?

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#24]
https://github.com/galatea-associates/gerrard-sl/blob/8cc9ab511444a5cd79930b5151b71e825f9d0c90/src/main/java/Agreements/Exchange.java#L163

Do you have to return dummy orders in situations like this?  I think it would make more sense if null was returned when you didn't get any matches.  Happy to discuss if the books suggest otherwise.

**Comment by Gala-Gerrard** [comment]
The createDummyOrder was a response to the Clean Code guideline that returning Null is generally considered bad convention - might be worth a discussion
