### ISSUE TITLE
Does this work for you?

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#32]
https://github.com/galatea-associates/gerrard-sl/blob/d36433222521ec0082408e81f40245b903188508/src/main/java/Initialisation/main.java#L65

I get an exception when I try to run this and have to set the file location to
"gerrard-sl\\config.yml"
for it to work

**Comment by Gala-Gerrard** [comment]
I've added a new commit which uses a prefix to each path of System.getProperties("user.dir") which should hopefully fix this, I won't close this issue until you can confirm that this has solved it for you.

**Comment by GalateaTom** [comment]
Checked, resolved
