### ISSUE TITLE
Should this be a method or a constant?

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#37]
https://github.com/galatea-associates/gerrard-sl/blob/8ff4f1b8fe87d8606b15fa9bc8ee858b171311f8/src/main/java/Entry_Points/CsvSplitBy.java#L9

**Comment by Gala-Gerrard** [comment]
I prefer the readability of comma() vs getComma(), although if it is too unconventional can always use a class variable
