### ISSUE TITLE
Comma defined multiple times

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#5]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/ReadWriteFiles.java#L129

Commas are defined a few times in this class (and maybe in other classes).  Look into how you can set things up so it only needs to be defined once in the entire project.

**Comment by Gala-Gerrard** [comment]
Isn't setting global variables generally advised against in Java? Could remove the declaration of csvSplitBy and just directly enter the comma as a delimiter in the .split() function instead?

**Comment by Gala-Gerrard** [comment]
Class created called CsvSplitBy which has a function called comma(), returning a "," to be used as a delimiter anywhere in the project
