### ISSUE TITLE
Potential to use an Enum here

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#6]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/Order.java#L11

The direction should always be BUY or SELL so it's bit risky to use a String here as then the direction could be something else.  Look into Java Enums as the direction variable could be good place to use them.

**Comment by Gala-Gerrard** [comment]
Changed all strings to enums
