### ISSUE TITLE
Why not return a String here?

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#8]
https://github.com/galatea-associates/gerrard-sl/blob/b70bd9aab1e8ccb9738f4799006ae1e6f1bb6259/src/main/java/ReadWriteFiles.java#L84

Strings are simpler than StringBuilders.  Could you return a String rather than a StringBuilder from orderToExchange (and anywhere else this happens)?

**Comment by Gala-Gerrard** [comment]
It could be done with String, although given the mutability of StringBuilder objects it makes more sense to keep it as a StringBuilder to improve computational efficiency

**Comment by Gala-Gerrard** [comment]
Changed to objects
